### ISSUE TITLE
sdkmanager.bat java issue

### ISSUE THREAD

**Issue by mamin27** [jmpessoa/lazandroidmodulewizard#481]
Java issue created during run of commands:

```sh
on command line terminal go to folder "sdk/tools/bin"

    run the command >>sdkmanager --update
    run the command >>sdkmanager "build-tools;30.0.2" "platforms;android-30"
```

[r25.2.5-windows](https://dl.google.com/android/repository/tools_r25.2.5-windows.zip)

in sdk/tools/bin is sdkmanager.bat file. I used it like
```sh
./sdkmanager --update
```

**Comment by afuriza** [comment]
I have the same problem, so I downloaded many of them manually. So, I have the SDK that already contains platform 30 for Windows if you want. I uploaded that here https://mega.nz/file/VlhFSLQZ#k0SGdjKcdNrfO5WvHJ-ExLjB6zzVkKiWzyDAmytsdDw

**Comment by lucas-04** [comment]
> Java issue created during run of commands:
> 
> ```shell
> on command line terminal go to folder "sdk/tools/bin"
> 
>     run the command >>sdkmanager --update
>     run the command >>sdkmanager "build-tools;30.0.2" "platforms;android-30"
> ```
> 
> [r25.2.5-windows](https://dl.google.com/android/repository/tools_r25.2.5-windows.zip)
> 
> in sdk/tools/bin is sdkmanager.bat file. I used it like
> 
> ```shell
> ./sdkmanager --update
> ```

Like this?

sdkmanager --update
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:103)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 4 more

if yes, you need set the java path.
Run command: set JAVA_HOME=path to the java folder

**Comment by mamin27** [comment]
Thanks it works. This issue could be closed.
